"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, ChevronDown, Copy, Info, Plus, RefreshCw, Sparkles, Trash2, UserRound, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { getLatestChanges, type ListType, type Snapshot } from "./comparison";

const blocked = new Set(["follow","following","followers","message","requested","remove","suggested","for","you","see","all","verified"]);
const valid = /^[a-zA-Z0-9._]{1,30}$/;
function parse(raw:string) {
  const lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean), found=new Set<string>(); let ignored=0;
  lines.forEach((line,i)=>{ const url=line.match(/(?:www\.)?instagram\.com\/([a-zA-Z0-9._]{1,30})/i); const at=line.match(/^@([a-zA-Z0-9._]{1,30})$/); let name=url?.[1]??at?.[1];
    if(!name&&valid.test(line)&&!blocked.has(line.toLowerCase())) { const near=[lines[i-1],lines[i+1]].map(x=>x?.toLowerCase()); if(near.some(x=>x==="follow"||x==="following"||x==="requested")||/[._0-9]/.test(line)||line===line.toLowerCase()) name=line; }
    if(name&&!blocked.has(name.toLowerCase())) found.add(name.toLowerCase()); else ignored++;
  }); return {usernames:[...found],ignored};
}
function DiffGroup({kind,items}:{kind:"appeared"|"disappeared"|"unchanged";items:string[]}){
 const labels={appeared:"Appeared",disappeared:"Disappeared",unchanged:"Unchanged"};
 return <details className={`diff-group ${kind}`} open={kind!=="unchanged"&&items.length>0}><summary><span><b>{labels[kind]}</b><small>{kind==="appeared"?"New in this snapshot":kind==="disappeared"?"No longer in this snapshot":"Present in both snapshots"}</small></span><strong>{items.length}</strong><ChevronDown size={17}/></summary>{items.length?<div className="diff-names">{items.map(u=><a key={u} href={`https://instagram.com/${u}`} target="_blank" rel="noreferrer">@{u}</a>)}</div>:<p className="no-change">No accounts here.</p>}</details>;
}
export default function Importer(){
 const [snapshots,setSnapshots]=useState<Snapshot[]>([]),[profile,setProfile]=useState(""),[listType,setListType]=useState<ListType>("following"),[raw,setRaw]=useState(""),[collected,setCollected]=useState<string[]>([]),[parts,setParts]=useState<{found:number;duplicates:number}[]>([]),[status,setStatus]=useState(""),[editing,setEditing]=useState(true);
 const [usage,setUsage]=useState({used:0,limit:3,remaining:3});
 const [agentEvent,setAgentEvent]=useState("");
 const [followingCount,setFollowingCount]=useState(""),[followersCount,setFollowersCount]=useState("");
 useEffect(()=>{const staged=sessionStorage.getItem("who-follows-profile")??"";sessionStorage.removeItem("who-follows-profile");fetch("/api/snapshots").then(r=>r.json()).then(d=>{const loaded:Snapshot[]=d.snapshots??[];setSnapshots(loaded);if(d.usage)setUsage(d.usage);if(staged){setProfile(staged);setEditing(true)}else if(loaded.length){setProfile(loaded[0].profileName);setEditing(false)}});},[]);
 const profiles=useMemo(()=>[...new Set(snapshots.map(s=>s.profileName))],[snapshots]);
 useEffect(()=>{
  if(!document.modelContext||!snapshots.length)return;
  const controller=new AbortController();
  Promise.resolve(document.modelContext.registerTool({name:"get_latest_changes",description:"Return the deterministic difference between the latest two user-provided snapshots for one saved Instagram profile and list type. Use appeared/disappeared without inferring motives or actual follow events.",inputSchema:{type:"object",properties:{profile:{type:"string",description:"A profile saved in the signed-in user's WhoFollows account."},list_type:{type:"string",enum:["following","followers"],description:"Whether to compare Following or Followers snapshots."}},required:["profile","list_type"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{const requestedProfile=typeof input.profile==="string"?input.profile:"",requestedType=input.list_type==="followers"?"followers":"following",result=getLatestChanges(snapshots,requestedProfile,requestedType);if(!result)return JSON.stringify({error:"At least two matching snapshots are required.",profile:requestedProfile.replace(/^@/,""),list_type:requestedType});setAgentEvent(`Shared a read-only ${requestedType} comparison for @${result.profile} with your browser agent.`);return JSON.stringify(result)}},{signal:controller.signal})).catch(()=>{});
  return()=>controller.abort();
 },[snapshots]);
 const previous=snapshots.find(s=>s.profileName===profile&&(s.listType??"following")===listType);
 const recommendation=useMemo<ListType|null>(()=>{const a=Number(followingCount),b=Number(followersCount);if(!a||!b||a===b)return null;return a<b?"following":"followers"},[followingCount,followersCount]);
 function choose(type:ListType){setListType(type);setCollected([]);setParts([]);setStatus("");}
 function addPart(){const result=parse(raw); if(!result.usernames.length){setStatus("We couldn't confidently find usernames. Try copying the loaded list again.");return;} const current=new Set(collected), fresh=result.usernames.filter(x=>!current.has(x)); setCollected([...collected,...fresh]);setParts([...parts,{found:result.usernames.length,duplicates:result.usernames.length-fresh.length}]);setRaw("");setStatus("");}
 async function save(){setStatus("Saving…");const res=await fetch("/api/snapshots",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({profileName:profile.replace(/^@/,"").toLowerCase(),listType,usernames:collected})});const data=await res.json();if(!res.ok){setStatus(data.error??"Could not save.");return;}setSnapshots([data.snapshot,...snapshots]);if(data.usage)setUsage(data.usage);setCollected([]);setParts([]);setStatus("");setEditing(false);}
 const diff=previous&&collected.length?{appeared:collected.filter(x=>!previous.usernames.includes(x)),disappeared:previous.usernames.filter(x=>!collected.includes(x)),unchanged:collected.filter(x=>previous.usernames.includes(x))}:null;
 const profileSnapshots=snapshots.filter(s=>s.profileName===profile), latestFollowing=profileSnapshots.find(s=>(s.listType??"following")==="following"), latestFollowers=profileSnapshots.find(s=>s.listType==="followers");
 const recentType=(latestFollowing&&latestFollowers?new Date(latestFollowing.createdAt)>new Date(latestFollowers.createdAt)?"following":"followers":latestFollowers?"followers":"following") as ListType;
 const recentSnapshots=profileSnapshots.filter(s=>(s.listType??"following")===recentType), latest=recentSnapshots[0], before=recentSnapshots[1];
 const latestComparison=getLatestChanges(snapshots,profile,recentType),lastAdded=latestComparison?.appeared??[],lastRemoved=latestComparison?.disappeared??[];
 function selectProfile(p:string){setProfile(p);setEditing(false);setStatus("");setCollected([]);setParts([])}
 function newProfile(){setProfile("");setEditing(true);setStatus("");setCollected([]);setParts([])}
 return <div className="app-grid"><aside className="sidebar"><div><p className="side-label">Profiles</p>{profiles.length?profiles.map(p=><button key={p} className={profile===p?"profile-row active":"profile-row"} onClick={()=>selectProfile(p)}>@{p}<span>{snapshots.filter(s=>s.profileName===p).length}</span></button>):<p className="empty-side">Your saved profiles will appear here.</p>}<button className="new-profile" onClick={newProfile}><Plus size={15}/>New profile</button><div className="usage-card"><div><span>WEEKLY CHECKS</span><b>{usage.remaining} of {usage.limit} left</b></div><div className="usage-dots">{Array.from({length:usage.limit},(_,i)=><i key={i} className={i<usage.used?"used":""}/>)}</div><small>Resets gradually over 7 days</small></div></div><div className="privacy-note"><Info size={17}/><p>We never ask for your Instagram password or access your account.</p></div></aside>
 {!editing&&latest?<section className="profile-dashboard"><div className="profile-hero"><div className="profile-avatar"><UserRound size={38}/></div><div><span>TRACKED PROFILE</span><h1>@{profile}</h1><p>Last updated {new Date(latest.createdAt).toLocaleDateString()}</p></div></div><div className="profile-stats"><div><span>Following</span><strong>{latestFollowing?.usernames.length.toLocaleString()??"—"}</strong><small>{latestFollowing?`Updated ${new Date(latestFollowing.createdAt).toLocaleDateString()}`:"Not added yet"}</small></div><div><span>Followers</span><strong>{latestFollowers?.usernames.length.toLocaleString()??"—"}</strong><small>{latestFollowers?`Updated ${new Date(latestFollowers.createdAt).toLocaleDateString()}`:"Not added yet"}</small></div><div><span>Snapshots</span><strong>{profileSnapshots.length}</strong><small>Saved comparisons</small></div></div><div className="latest-changes"><div className="changes-heading"><div><span>LATEST CHANGES</span><h2>{before?`Since ${new Date(before.createdAt).toLocaleDateString()}`:"Waiting for the next snapshot"}</h2></div><b>{recentType}</b></div>{before?<div className="change-preview"><div className="change-plus"><strong>+{lastAdded.length}</strong><span>appeared</span>{lastAdded.slice(0,3).map(u=><small key={u}>@{u}</small>)}</div><div className="change-minus"><strong>−{lastRemoved.length}</strong><span>disappeared</span>{lastRemoved.slice(0,3).map(u=><small key={u}>@{u}</small>)}</div></div>:<p className="first-snapshot-note">Add one more snapshot later and the exact changes will appear here.</p>}</div>{agentEvent&&<div className="agent-event"><Sparkles size={17}/><div><b>WebMCP request completed</b><span>{agentEvent}</span></div></div>}<Button className="update-button" onClick={()=>{setListType(recentType);setEditing(true)}}><RefreshCw size={18}/>Update info</Button></section>:
 <section className="import-card"><div className="step-kicker">{previous?"UPDATE PROFILE":"NEW SNAPSHOT"}</div><h1>{previous?`Update @${profile}`:"Create a quiet reference point"}</h1><p className="section-copy">Choose the shorter list when you can—it means less scrolling and copying. Who Follows? compares either <b>Following</b> or <b>Followers</b>.</p>
 <label className="field-label" htmlFor="profile">Profile you’re checking</label><div className="profile-input"><span>@</span><Input id="profile" value={profile} onChange={e=>setProfile(e.target.value.replace(/^@/,""))} placeholder="username"/></div>
 <div className="count-helper"><div className="helper-heading"><UsersRound size={18}/><div><b>Which list is shorter?</b><span>Enter the visible totals from the Instagram profile.</span></div></div><div className="count-inputs"><label>Following<Input inputMode="numeric" value={followingCount} onChange={e=>setFollowingCount(e.target.value.replace(/\D/g,""))} placeholder="e.g. 340"/></label><label>Followers<Input inputMode="numeric" value={followersCount} onChange={e=>setFollowersCount(e.target.value.replace(/\D/g,""))} placeholder="e.g. 1240"/></label></div>{recommendation&&<p className="recommendation"><Sparkles size={15}/>Less copying: choose <b>{recommendation === "following"?"Following":"Followers"}</b>.</p>}</div>
 <div className="list-choice"><button className={listType==="following"?"active":""} onClick={()=>choose("following")}><span>Following</span><small>Accounts this profile follows</small>{recommendation==="following"&&<b>SHORTER</b>}</button><button className={listType==="followers"?"active":""} onClick={()=>choose("followers")}><span>Followers</span><small>Accounts following this profile</small>{recommendation==="followers"&&<b>SHORTER</b>}</button></div>
 <div className="paste-instruction"><b>Now copy the list from Instagram</b><ol><li>Open Instagram in your browser.</li><li>Open this profile’s <b>{listType === "following"?"Following":"Followers"}</b> list.</li><li>Copy the loaded accounts and paste them below. For a long list, repeat this in smaller parts.</li></ol></div>
 <label className="field-label" htmlFor="list">Paste one part of {listType === "following"?"Following":"Followers"}</label><Textarea id="list" value={raw} onChange={e=>setRaw(e.target.value)} placeholder={"Paste the copied Instagram list here…"} className="paste-area"/><Button className="add-button" onClick={addPart} disabled={!raw.trim()}><Plus size={18}/>Add this part</Button>
 {parts.length>0&&<div className="parts-list">{parts.map((x,i)=><div key={i}><span><Check size={15}/>Part {i+1}</span><b>{x.found} found{x.duplicates?` · ${x.duplicates} duplicates`:""}</b></div>)}</div>}
 {collected.length>0&&<div className="review-panel"><div className="total-line"><div><small>TOTAL DETECTED</small><strong>{collected.length} unique accounts</strong></div><button onClick={()=>{setCollected([]);setParts([])}}><Trash2 size={16}/>Clear</button></div><div className="username-cloud">{collected.slice(0,40).map(u=><span key={u}>@{u}<button onClick={()=>setCollected(collected.filter(x=>x!==u))}>×</button></span>)}{collected.length>40&&<span>+{collected.length-40} more</span>}</div></div>}
 {diff&&<div className="diff-preview"><div className="diff-title"><div><h2>Exactly what changed</h2><p>Compared with the last {listType} snapshot from {new Date(previous!.createdAt).toLocaleDateString()}.</p></div><button onClick={()=>navigator.clipboard.writeText([...diff.appeared.map(x=>`+ @${x}`),...diff.disappeared.map(x=>`- @${x}`)].join("\n"))}><Copy size={16}/>Copy changes</button></div><DiffGroup kind="appeared" items={diff.appeared}/><DiffGroup kind="disappeared" items={diff.disappeared}/><DiffGroup kind="unchanged" items={diff.unchanged}/></div>}{status&&<p className="status-message">{status}</p>}<Button className="save-button" onClick={save} disabled={!profile.trim()||!collected.length}>Save {listType} snapshot</Button></section>}</div>;
}
